INSERT OR IGNORE INTO classifier_rules (
  rule_key, path_pattern, op_filter_json, value_filter_json, severity,
  category, timing_sensitive, description, active, created_at
) VALUES
(
  'primary_outcome_any_change',
  '/protocolSection/outcomesModule/primaryOutcomes/**',
  '["add","remove","replace"]',
  '{}',
  'critical',
  'primary_outcome_change',
  1,
  'Any add/remove/replace under primary outcome measures is critical review priority.',
  1,
  datetime('now')
),
(
  'secondary_outcome_any_change',
  '/protocolSection/outcomesModule/secondaryOutcomes/**',
  '["add","remove","replace"]',
  '{}',
  'high',
  'secondary_outcome_change',
  1,
  'Any add/remove/replace under secondary outcome measures is high review priority.',
  1,
  datetime('now')
),
(
  'design_info_change',
  '/protocolSection/designModule/designInfo/**',
  '["add","remove","replace"]',
  '{}',
  'high',
  'design_change',
  1,
  'Design information changes can alter allocation, masking, model, or purpose and need review.',
  1,
  datetime('now')
),
(
  'phase_change',
  '/protocolSection/designModule/phases/**',
  '["add","remove","replace"]',
  '{}',
  'high',
  'design_change',
  1,
  'Trial phase changes are high review-priority design changes.',
  1,
  datetime('now')
),
(
  'arms_or_interventions_change',
  '/protocolSection/armsInterventionsModule/**',
  '["add","remove","replace"]',
  '{}',
  'high',
  'arm_intervention_change',
  1,
  'Arms or interventions changes can alter treatment/comparator structure.',
  1,
  datetime('now')
),
(
  'terminal_status_change',
  '/protocolSection/statusModule/overallStatus',
  '["replace"]',
  '{"in":["TERMINATED","SUSPENDED","WITHDRAWN"]}',
  'high',
  'status_termination',
  0,
  'Status changed to terminated, suspended, or withdrawn; whyStopped content determines whether critical review is warranted.',
  1,
  datetime('now')
),
(
  'eligibility_criteria_change',
  '/protocolSection/eligibilityModule/eligibilityCriteria',
  '["add","remove","replace"]',
  '{}',
  'high',
  'eligibility_change',
  1,
  'Eligibility criteria changes can alter the studied population.',
  1,
  datetime('now')
),
(
  'enrollment_count_change',
  '/protocolSection/designModule/enrollmentInfo/count',
  '["replace"]',
  '{}',
  'high',
  'enrollment_change',
  1,
  'Enrollment count changes can signal scope or feasibility shifts.',
  1,
  datetime('now')
),
(
  'enrollment_type_change',
  '/protocolSection/designModule/enrollmentInfo/type',
  '["replace"]',
  '{}',
  'high',
  'enrollment_change',
  1,
  'Enrollment type changes from anticipated to actual or similar are high review priority.',
  1,
  datetime('now')
),
(
  'why_stopped_change',
  '/protocolSection/statusModule/whyStopped',
  '["add","remove","replace"]',
  '{}',
  'high',
  'status_termination',
  0,
  'Why-stopped changes explain discontinuation and need review.',
  1,
  datetime('now')
),
(
  'primary_completion_timeline_change',
  '/protocolSection/statusModule/primaryCompletionDateStruct/**',
  '["add","remove","replace"]',
  '{}',
  'medium',
  'timeline_shift',
  0,
  'Primary completion date changes are operational timeline signals.',
  1,
  datetime('now')
),
(
  'completion_timeline_change',
  '/protocolSection/statusModule/completionDateStruct/**',
  '["add","remove","replace"]',
  '{}',
  'medium',
  'timeline_shift',
  0,
  'Completion date changes are operational timeline signals.',
  1,
  datetime('now')
),
(
  'start_timeline_change',
  '/protocolSection/statusModule/startDateStruct/**',
  '["add","remove","replace"]',
  '{}',
  'medium',
  'timeline_shift',
  0,
  'Start date changes are operational timeline signals.',
  1,
  datetime('now')
),
(
  'contact_admin_change',
  '/protocolSection/contactsLocationsModule/centralContacts/**',
  '["add","remove","replace"]',
  '{}',
  'low',
  'administrative_contact_change',
  0,
  'Central contact updates are usually administrative.',
  1,
  datetime('now')
);
