from __future__ import annotations

import argparse
import json
from pathlib import Path
import sqlite3
import sys
from typing import Any


TABLES = [
    "trials",
    "trial_snapshots",
    "trial_versions",
    "trial_patches",
    "materiality_events",
    "evidence_records",
    "classifier_rules",
    "case_studies",
    "ingest_runs",
]

JSON_COLUMNS = {
    "conditions_json",
    "interventions_json",
    "phase_json",
    "current_record_json",
    "record_json",
    "module_labels_json",
    "unposted_events_json",
    "patch_json",
    "changed_paths_json",
    "changed_modules_json",
    "op_counts_json",
    "categories_json",
    "deterministic_rules_json",
    "value_signals_json",
    "claims_supported_json",
    "claims_not_supported_json",
    "canonical_json",
    "op_filter_json",
    "value_filter_json",
    "query_json",
    "relaxation_json",
}

BOOLEAN_COLUMNS = {
    "has_results",
    "review_not_passed",
    "needs_human_review",
    "timing_sensitive",
    "active",
}

TIMESTAMPTZ_COLUMNS = {
    "fetched_at",
    "created_at",
    "verified_at",
    "started_at",
    "completed_at",
    "generated_at",
}

IDENTITY_TABLES = {
    "trial_snapshots",
    "trial_versions",
    "trial_patches",
    "materiality_events",
    "classifier_rules",
    "case_studies",
    "ingest_runs",
}


def quote_text(value: Any) -> str:
    return "'" + str(value).replace("'", "''") + "'"


def quote_json(value: Any) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, str):
        parsed = json.loads(value)
    else:
        parsed = value
    encoded = json.dumps(parsed, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    return f"{quote_text(encoded)}::jsonb"


def quote_value(column: str, value: Any) -> str:
    if value is None:
        return "NULL"
    if column in JSON_COLUMNS:
        return quote_json(value)
    if column in BOOLEAN_COLUMNS:
        return "true" if bool(value) else "false"
    if column in TIMESTAMPTZ_COLUMNS:
        return f"{quote_text(value)}::timestamptz"
    if isinstance(value, int | float):
        return str(value)
    return quote_text(value)


def batched(values: list[str], size: int) -> list[list[str]]:
    return [values[index : index + size] for index in range(0, len(values), size)]


def table_columns(connection: sqlite3.Connection, table: str) -> list[str]:
    rows = connection.execute(f"PRAGMA table_info({table})").fetchall()
    return [row["name"] for row in rows]



def table_exists(connection: sqlite3.Connection, table: str) -> bool:
    row = connection.execute(
        "SELECT name FROM sqlite_master WHERE type='table' AND name=?",
        (table,),
    ).fetchone()
    return row is not None


def dump_table(
    *,
    connection: sqlite3.Connection,
    table: str,
    batch_size: int,
    output: list[str],
) -> None:
    if not table_exists(connection, table):
        return
    columns = table_columns(connection, table)
    quoted_columns = ", ".join(f'"{column}"' for column in columns)
    rows = connection.execute(f"SELECT * FROM {table}").fetchall()
    if not rows:
        return

    values = []
    for row in rows:
        values.append("(" + ", ".join(quote_value(column, row[column]) for column in columns) + ")")

    for batch in batched(values, batch_size):
        output.append(f"INSERT INTO {table} ({quoted_columns}) VALUES")
        output.append(",\n".join(batch))
        output.append("ON CONFLICT DO NOTHING;\n")


def build_export(sqlite_path: Path, *, truncate: bool, batch_size: int) -> str:
    connection = sqlite3.connect(sqlite_path)
    connection.row_factory = sqlite3.Row
    try:
        output = [
            "-- Generated by scripts/sqlite_to_postgres.py",
            "-- Run postgres/migrations/*.sql before applying this export.",
            "BEGIN;",
        ]
        if truncate:
            present = [t for t in TABLES if table_exists(connection, t)]
            table_list = ", ".join(present)
            output.append(f"TRUNCATE {table_list} RESTART IDENTITY CASCADE;")

        for table in TABLES:
            dump_table(connection=connection, table=table, batch_size=batch_size, output=output)

        for table in IDENTITY_TABLES:
            output.append(
                "SELECT setval(pg_get_serial_sequence("
                f"{quote_text(table)}, 'id'), "
                f"COALESCE((SELECT max(id) FROM {table}), 1), "
                f"COALESCE((SELECT max(id) FROM {table}), 0) > 0);"
            )

        output.append("COMMIT;")
        return "\n".join(output) + "\n"
    finally:
        connection.close()


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Export a TrialDiff SQLite database as Postgres-compatible INSERT statements.",
    )
    parser.add_argument("sqlite", type=Path, help="Path to the source SQLite database.")
    parser.add_argument("--output", type=Path, help="Destination .sql file. Defaults to stdout.")
    parser.add_argument("--truncate", action="store_true", help="Truncate target tables before inserting.")
    parser.add_argument("--batch-size", type=int, default=100, help="Rows per INSERT statement.")
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    sql = build_export(args.sqlite, truncate=args.truncate, batch_size=args.batch_size)
    if args.output:
        args.output.write_text(sql, encoding="utf-8")
    else:
        sys.stdout.write(sql)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
